# Generated by Django 4.2.13 on 2024-07-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
